// import Head from 'next/head'
import Link from 'next/link'
// import styles from '../styles/Home.module.css'

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           <Link href="/plot/ground-test">
//             <a>Plot</a>
//           </Link>
//         </h1>
//       </main>
//     </div>
//   )
// }
import { Container } from '@chakra-ui/react'
import PlotSetting from '../components/PlotSetting'
import { RecoilRoot } from 'recoil'

export default function Home() {
  return (
    <>
      <RecoilRoot>
        <Container maxW="container.xl" p={5}>
          <Link href="/plot/ground-test">
            <a>Plot</a>
          </Link>
          <PlotSetting />
        </Container>
      </RecoilRoot>
    </>
  )
}
